[tool.black]
line-length = 80
target-version = ['py39']
# experimental_string_processing = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''


# [tool.isort]
# line_length = 80
# src_paths = ''
# profile = 'black'


[tool.pytest.ini_options]
addopts = "--cov=phd_flow --cov-report html"
testpaths = ['test']
filterwarnings = [
    'ignore:.*Create unlinked descriptors is going to go away.*:DeprecationWarning',
    # https://github.com/tensorflow/tensorboard/pull/5138
    'ignore:.*is a deprecated alias for the builtin.*:DeprecationWarning',
]

[[tool.mypy.overrides]]
module = [
    "b2sdk",
    "b2sdk.*",
    "b2sdk.v2",
    "matplotlib",
    "pandas",
    "sklearn",
    "sklearn.*",
    "coverage",
]
ignore_missing_imports = true
