name: Deploy docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ubuntu-latest-cache-v2-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -e .

      - name: Build docs
        run: time ./scripts/build_docs.sh

      - name: Deploy docs
        env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: .github/deploy-gh-pages.sh
